[package]
name = "grep-lite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
colored = "2.0.0"
colorize = "0.1.0"
regex = "1"
